from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol


@dataclass(frozen=True)
class DestinationProbe:
    accessible: bool
    scope: str
    detail: str


class MediaSource(Protocol):
    """Authorized media access; ingestion must still use the shared TaskDB."""

    async def get_messages(self, entity: int, *, ids: int) -> Any: ...

    async def download_media(
        self, message: Any, *, file: Any,
        progress_callback: Callable[[int, int], None],
    ) -> Any: ...


class UploadStream(Protocol):
    async def write(self, data: bytes) -> int: ...
    def tell(self) -> int: ...
    def flush(self) -> None: ...
    async def finish(self) -> None: ...
    async def abort(self) -> None: ...


class Destination(Protocol):
    """Size verification is receipt by this backend, not confirmation by 115."""

    async def probe(self) -> DestinationProbe: ...
    async def healthy(self) -> bool: ...
    async def upload(
        self, local_path: Path, remote_temp: str,
        *, progress: Callable[[int, float], None] | None = None,
    ) -> None: ...
    async def open_upload_stream(
        self, remote_temp: str, exact_size: int,
    ) -> UploadStream: ...
    async def remote_size(self, relative_path: str) -> int: ...
    async def exists(self, relative_path: str) -> bool: ...
    async def move(self, source: str, destination: str) -> None: ...
    async def remove(self, relative_path: str) -> None: ...
    async def list_staging_objects(self) -> list[tuple[int, str]]: ...
